name: swaply
description: A marketplace app for Zimbabwe
publish_to: 'none'
version: 1.0.0+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 闁哄秶顭堢缓鐐瑹濠靛﹦顩?
  intl: any
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.3
  uuid: ^3.0.7

  # Supabase
  supabase_flutter: 2.7.0
  google_sign_in: ^6.2.1
  # 闁搞儱澧芥晶鏍儎缁嬪灝褰?
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  file_picker: ^10.3.3

  # 缂傚啯鍨圭划鍫曞椽瀹€鍐惧悋閻?
  http: ^1.1.0
  url_launcher: 6.3.0

  # 闁告帒妫旈棅鈺呭礉閻旇鍘?
  share_plus: ^12.0.0

  # 闁稿繑婀圭划?
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.5
  path: ^1.9.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  supabase: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1   # 闁?闁搞儳鍋撻悥锝夋偨閻旂鐏囩€规悶鍎遍崣?

# flutter_launcher_icons 闂佹澘绉堕悿?
# 濞达絿濮峰▓鎴炵▔婢跺﹦鐐婃繝褎鍔曞ù姗€妫侀埀顒傛啺娴ｈ鏉归柛锔荤厜缁?
# assets/app_icons/app_icon.png       闁?024x1024闁挎稑顓縊S/闁糕晛鎼崳顖炴晬?
# assets/app_icons/app_icon_fg.png    闁?080x1080闁挎稑鐭傞埀顒€绻戝Σ鎴﹀礈瀹ュ棙鐝柨娑樼搼ndroid闁?
# assets/app_icons/app_icon_bg.png    闁?080x1080闁挎稑鑻悿鍕嚌?婵炴挻鍔曡ぐ澶愭嚄鐏炵偓鐝柨娑樼搼ndroid闁?
flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: assets/app_icons/app_icon.png
  adaptive_icon_foreground: assets/app_icons/app_icon_fg.png
  adaptive_icon_background: assets/app_icons/app_icon_bg.png
  # 闁告瑯鍨堕埀顒€顧€缁辩檰ndroid 13+ 闁告娲濇竟濠囧炊閻愵剛鍨奸柨娑樼墛瑜颁焦绗熷☉妤冾伇鐎殿喚濮烽崙浠嬫嚌閹绘帒绀嬮柤纭呭皺婢ф宕滃鍡樼彲闁?
  # adaptive_icon_monochrome: assets/app_icons/app_icon_fg_mono.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/icons/trending.png
    - assets/icons/vehicles.png
    - assets/icons/property.png
    - assets/icons/beauty_personal_care.png
    - assets/icons/jobs.png
    - assets/icons/babies_kids.png
    - assets/icons/services.png
    - assets/icons/leisure_activities.png
    - assets/icons/repair_construction.png
    - assets/icons/home_furniture_appliances.png
    - assets/icons/pets.png
    - assets/icons/electronics.png
    - assets/icons/phones_tablets.png
    - assets/icons/seeking_work_cvs.png
    - assets/icons/fashion.png
    - assets/icons/food_agriculture_drinks.png

    - assets/images/
    - assets/images/trending_items/
    - assets/images/trending_items/item1/
    - assets/images/trending_items/item1/1.jpg
    - assets/images/trending_items/item2/
    - assets/images/trending_items/item2/1.jpg
    - assets/images/trending_items/item3/
    - assets/images/trending_items/item3/1.jpg

flutter_intl:
  enabled: false

