# android/gradle.properties
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# 1. (??) ????????????? JVM ??????
org.gradle.configuration-cache=false

# 2. JVM ????? + Java 17 ????
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED

# 3. (??) ????????? C:/D: ?????
kotlin.incremental=false

# 4. Kotlin ??????
kotlin.daemon.jvmargs=-Xmx2048m --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED

# 5. AndroidX
android.useAndroidX=true
android.enableJetifier=true