# android/gradle.properties

# JVM/Gradle ?? & ??
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=4g -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
kotlin.daemon.jvm.options=-Xmx2g

# ????????? OOM
org.gradle.parallel=false
org.gradle.workers.max=2

# ????
android.useAndroidX=true
android.enableJetifier=true
